### ISSUE TITLE
eslint-plugin-prettier 好像不被 prettier 官方推荐

### ISSUE THREAD

**Issue by s5s5** [haixiangyan/linter-tutorial#8]
这里写的 https://prettier.io/docs/en/integrating-with-linters.html#notes

**Comment by haixiangyan** [comment]
这里 Note 的意思是：当你在网上找 eslint 和 prettier 相关的 NPM 包时，你会发现有很多名字类似的包，比如 eslint-recommend-prettier, prettier-eslint-recommend 之类的，这些包一般来说 Star 数很低，并不是官方维护的，所以官方不推荐这些库。
